/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 11 23:21:10 GMT 2022
 */

package org.gedcom4j.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.gedcom4j.exception.ValidationException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ValidationException_ESTest extends ValidationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ValidationException validationException0 = new ValidationException("");
      MockThrowable mockThrowable0 = new MockThrowable(validationException0);
      ValidationException validationException1 = new ValidationException(mockThrowable0);
      assertFalse(validationException1.equals((Object)validationException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ValidationException validationException0 = new ValidationException("");
      ValidationException validationException1 = new ValidationException("", validationException0);
      assertFalse(validationException1.equals((Object)validationException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ValidationException validationException0 = new ValidationException();
  }
}
