/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 08 18:49:29 GMT 2022
 */

package com.inspiring.pugtsdb.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.inspiring.pugtsdb.exception.PugConversionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PugConversionException_ESTest extends PugConversionException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      PugConversionException pugConversionException0 = null;
      try {
        pugConversionException0 = new PugConversionException((byte[]) null, class0, (-316));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.inspiring.pugtsdb.exception.PugConversionException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      Class<Object> class0 = Object.class;
      PugConversionException pugConversionException0 = new PugConversionException(byteArray0, class0, 944);
  }
}
